name: Build and deploy Python project to Azure Function App - qq-mail

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: python -m unittest discover -s tests -v

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_EA2772185179449B837582B07070FBF3 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7C3A36018225471E827FF6D758A3F260 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C69A221D04C544A6A06A646B47BDD611 }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: "qq-mail"
          package: "."
          sku: "flexconsumption"
          remote-build: true
          respect-funcignore: true
